version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
    working_directory: /home/builder/shovon668
    steps:
      - run:
          name: Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/shovon668/android_kernel_realme_sm6150/lineage-17.1/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
